---
title: "Assignment"
author: "Scott Stoltzman"
date: "7/15/2019"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("mlbench")
library('GGally')
library("tidyverse")
library('caret')
library('plotROC')
set.seed(123)

data("PimaIndiansDiabetes") #loads dataframe for PimaIndiansDiabetes dataset
```

```{r}
dat = as.data.frame(PimaIndiansDiabetes) # MUST do for caret to work properly
head(dat)
```


# What are we going to try to predict?
Can we predict `pos` or `neg` outcome for diabetes?


```{r, warning=FALSE, message=FALSE}
# WARNING: takes a little while to process
ggpairs(dat)
```


# Separate out test vs train
```{r}
training_split = 0.75 #50% data for train, 50% for test
smp_size = floor(training_split * nrow(dat))
dat_index = sample(seq_len(nrow(dat)), size = smp_size)
dat_train = dat[dat_index,]
dat_test = dat[-dat_index,]
```


# Train your model

# Naive Bayes

## First try using defaults
```{r, warning=FALSE}
tctrl = trainControl(method = 'cv',
                     number = 10,
                     savePredictions = TRUE,
                     classProbs = TRUE)

mod_nb = train(dat_train %>% select(-diabetes), 
                dat_train$diabetes, 
                method = 'nb',
                trControl=tctrl)

pred_nb = predict(mod_nb, dat_test, type = 'prob')
```

```{r}
mod_nb
```

# Plot the ROC 
write a function for making these plots?
```{r, warning=FALSE}
df = dat_test %>% bind_cols(pred_nb) 
rocplot_nb <- ggplot(df, aes(m = pos, d = diabetes)) + 
  geom_roc() + 
  style_roc(theme = theme_grey) + 
  ggtitle('Naive Bayes')
rocplot_nb
```



# Logistic Regression
```{r}
tctrl = trainControl(method = 'cv',
                     number = 10,
                     savePredictions = TRUE,
                     p = 0.8,
                     classProbs = TRUE)

mod_logreg = train(dat_train %>% select(-diabetes), 
                dat_train$diabetes, 
                method="glm", 
                family="binomial",
                trControl=tctrl)

pred_logreg = predict(mod_logreg, dat_test, type = 'prob')
```

# Plot the ROC 
```{r, warning=FALSE}
df = dat_test %>% bind_cols(pred_logreg)
rocplot_logreg <- ggplot(df, aes(m = pos, d = diabetes)) + 
  geom_roc() + 
  style_roc(theme = theme_grey) + 
  ggtitle('Logistic Regression')
rocplot_logreg
```


# KNN
```{r}
tctrl = trainControl(method = 'cv',
                     number = 10,
                     savePredictions = TRUE,
                     p = 0.8,
                     classProbs = TRUE)

mod_knn = train(dat_train %>% select(-diabetes), 
                dat_train$diabetes, 
                method="knn", 
                trControl=tctrl)

pred_knn = predict(mod_knn, dat_test, type = 'prob')
```


# Plot the ROC 
```{r, warning=FALSE}
df = dat_test %>% bind_cols(pred_knn) 
rocplot_knn <- ggplot(df, aes(m = pos, d = diabetes)) + 
  geom_roc() + 
  style_roc(theme = theme_grey) + 
  ggtitle('K-Nearest Neighbors')
rocplot_knn
```



# Combine all models together
```{r}
results = resamples(list(mod_nb, mod_logreg, mod_knn))
summary(results)
```


```{r}
bwplot(results)
```



```{r}

```



